#!/usr/bin/env python3
"""Convert an image into a 1-bit C header for the clip-region demo.

  ./img_gen.py SOURCE [-o demo_image.h] [-n IMG] [-s 112] [--threshold N] [--invert]

Output bits are row-major, MSB first; a set bit means ink (black). The image
is scaled to fit within an S x S box (aspect preserved) and, by default,
Floyd-Steinberg dithered, which reads far better than a hard threshold on a
mono panel. Pass --threshold to use a flat cutoff instead.

-n/--name sets the C symbol prefix (e.g. IMG -> IMG_W/IMG_H/img_bits) so a
second image can live in its own header without clashing.
"""
import argparse
import os
import sys

from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("-o", "--out", default=os.path.join(
        os.path.dirname(__file__), "demo_image.h"))
    ap.add_argument("-n", "--name", default="IMG",
                    help="C symbol prefix (default IMG)")
    ap.add_argument("-s", "--size", type=int, default=112,
                    help="fit within this square (px)")
    ap.add_argument("--threshold", type=int, default=None,
                    help="flat cutoff 0-255 instead of dithering")
    ap.add_argument("--invert", action="store_true",
                    help="swap ink/background")
    args = ap.parse_args()

    img = Image.open(args.source).convert("L")
    img.thumbnail((args.size, args.size), Image.LANCZOS)

    if args.threshold is None:
        bw = img.convert("1")            # Floyd-Steinberg dither
    else:
        bw = img.point(lambda p: 255 if p >= args.threshold else 0, "1")

    w, h = bw.size
    px = bw.load()
    stride = (w + 7) // 8
    data = bytearray(stride * h)
    for y in range(h):
        for x in range(w):
            dark = px[x, y] == 0          # PIL "1": 0 = black
            if args.invert:
                dark = not dark
            if dark:
                data[y * stride + (x >> 3)] |= 0x80 >> (x & 7)

    pre = args.name.upper()
    sym = args.name.lower()
    guard = pre + "_IMAGE_H"
    with open(args.out, "w") as f:
        f.write("/* Generated by img_gen.py from %s */\n" %
                os.path.basename(args.source))
        f.write("#ifndef %s\n#define %s\n\n" % (guard, guard))
        f.write("#define %s_W %d\n#define %s_H %d\n#define %s_STRIDE %d\n\n"
                % (pre, w, pre, h, pre, stride))
        f.write("static const unsigned char %s_bits[] = {\n" % sym)
        for i in range(0, len(data), 12):
            row = ", ".join("0x%02x" % b for b in data[i:i + 12])
            f.write("\t" + row + ",\n")
        f.write("};\n\n#endif /* %s */\n" % guard)

    print("%s: %dx%d (%s) -> %s" %
          (sym, w, h, "threshold" if args.threshold else "dither", args.out),
          file=sys.stderr)


if __name__ == "__main__":
    main()
